### ISSUE TITLE
Carousel button borders only 3/4 appearing

### ISSUE THREAD

**Issue by quintoncables** [troop-370/troop370#107]
[https://drive.google.com/file/d/1gMMT5dlXNs2Zpv7vr7DyfVuhSYcMO5-g/view?usp=sharing](https://drive.google.com/file/d/1gMMT5dlXNs2Zpv7vr7DyfVuhSYcMO5-g/view?usp=sharing)
Occurs on chrome canary & edge dev

**Comment by jackbuehner** [comment]
This can be seen on troop370atlanta.org/index.html

I have no idea why this is happening.

It fixes itself when right clicking the button.
