### ISSUE TITLE
Map of Eagle Scout projects is broken

### ISSUE THREAD

**Issue by quintoncables** [troop-370/troop370#12]
Map displays a dialogue: "Please notify the map administrator that this map exceeded the usage limits of the free tier."

**Comment by jackbuehner** [comment]
Sorry, that's my fault. I refreshed the page at least 50 times during some testing of a different navigation method.

The map only allows 100 free map views. That is usually plenty, but I used them all up during testing. I'll have to remember to not use that page for testing in the future.

**Comment by jackbuehner** [comment]
We will not be paying for a subscription that adds more views since it will reset in ten days.
