### ISSUE TITLE
Add announcement: Woodruff Merit Badge Sign-Up

### ISSUE THREAD

**Issue by jackbuehner** [troop-370/troop370#137]
> Merit Badge sign-ups for Woodruff Summer Camp
> 
> It's time to make your selections for summer camp! Fill out this form before March 23rd so we know what to register for.
> 
> If you have any questions contact Jeff Hunt. 
> 
> https://forms.gle/MzXumknnn31BDW9m6

To be displayed from 24FEB2020 through 24MAR2020

**Comment by jackbuehner** [comment]
@quintoncables Can you add this?
It would require a carousel card on the home page and a new temporary page in the events category for the announcement ([example](https://troop370atlanta.org/events/camp-cards.html)).

**Comment by quintoncables** [comment]
Yeah just give me some time
