### ISSUE TITLE
Add 2020 high adventure to camps/high adventure page

### ISSUE THREAD

**Issue by jackbuehner** [troop-370/troop370#15]
I know many high adventure trips are planned for 2020. For the trips that are planned, the following needs to happen:
* determine which trips are occurring
* determine the dates of the trips
* retrieve sign up links
* create a description for each trip

**Comment by quintoncables** [comment]
for now, we can put all of the info weve gathered in the shared google doc

**Comment by jackbuehner** [comment]
@quintoncables Put the info here instead
