### ISSUE TITLE
Replace weekly newsletters page with a communication overview page

### ISSUE THREAD

**Issue by jackbuehner** [troop-370/troop370#16]
Currently, the weekly newsletters page just had a button to sign up for the emails. A revamped page should include the email sign-up, the remind sign-up, and a join link for the Facebook group. It should also mention other social media and the SmugMug.

The new page should be named `communication.html`. In the renaming process, it is import that `email-newsletters.html` is redirected to `communication.html`.

The work for this should occur on a different branch and be tested once completed before deployment to the master branch.

**Comment by quintoncables** [comment]
also, the top banner text needs more padding

**Comment by jackbuehner** [comment]
> 
> 
> also, the top banner text needs more padding

@quintoncables Can you clarify what you are talking about?

**Comment by quintoncables** [comment]
as for that padding, that is addressed in another issue. has this new communication page been finished? I see that youve done a lot of work in that branch. i can test it out some if youd like.
