### ISSUE TITLE
Add tutorial for scouts to update their troopmaster details

### ISSUE THREAD

**Issue by jackbuehner** [troop-370/troop370#22]
We need a page with screenshots that explains the importance of updating the details and setup a to do so.

**Comment by jackbuehner** [comment]
The troop is considering switching from using Constant Contact for the email blasts to Troopmaster. This document is needed very soon so they can start ensuring people have updated their information on Troopmaster.

**Comment by quintoncables** [comment]
I'm happy to do this, I just need to know how it should be implemented
