### ISSUE TITLE
encrypted page app bar padding and margin is incorrect

### ISSUE THREAD

**Issue by quintoncables** [troop-370/troop370#30]
attached is an example image of the issue
![screenshot 2019-02-11 at 10 17 01 am](https://user-images.githubusercontent.com/46767928/52572681-5c8d4180-2de6-11e9-8bc7-cd7acef86fbd.png)

**Comment by quintoncables** [comment]
does this header use a specific class or do we have to fix each individually? I cant tell due to the encrypted code.

**Comment by jackbuehner** [comment]
I can't remember, but you can download the page by right clicking it in Firefox and chosing view page source.
