### ISSUE TITLE
Kyle Wilson's Eagle Project is missing the location

### ISSUE THREAD

**Issue by jackbuehner** [troop-370/troop370#42]
On the [Eagle Scout Honor Roll page](https://troop370atlanta.org/eagle-scout-honor-roll.html), it says:

|Name|Eagle Date|Project|Hours|
|---|---|---|---|
|Kyle Wilson | 10/13/2015 |Built benches and upgraded the athletic field at ________ Church. |75|

**Comment by jackbuehner** [comment]
@evansclan Do you know where he did his project?

**Comment by evansclan** [comment]
North Atlanta Church of Christ, 5676 Roberts Dr, Dunwoody, GA 30338.

**Comment by jackbuehner** [comment]
Thanks. I've fixed it in the spreadsheet, so the project location should now appear on the website.
