### ISSUE TITLE
Add pictures for Troop 370 leadership to the current leadership page

### ISSUE THREAD

**Issue by jackbuehner** [troop-370/troop370#49]
Only pictures and names should be included. Pictures should be taken at the same location for constancy. Scouts should wear their uniform in their pictures. Do not include contact information on this page - it should be separate (see #8). 

Should it be password protected even though it only it does not have contact information? @Gulluk do you have any thoughts on this?

**Comment by quintoncables** [comment]
I do not think it should be password protected. I think it should be the second page honestly because its a tangible representation that we're a boy lead troop. put only the first names in the public section and then put the full name and contact info in the encrypted section

**Comment by quintoncables** [comment]
also, should we start a folder for leadership images in src?

**Comment by quintoncables** [comment]
lets move this issue to the rewrite. no work should be done on this outside of the rewrite

**Comment by jackbuehner** [comment]
> also, should we start a folder for leadership images in src?

We will have a separate folder.

> lets move this issue to the rewrite. no work should be done on this outside of the rewrite

Agreed. Let's pause work on this until the rewrite is finished.

**Comment by jackbuehner** [comment]
I'm closing this issue for now because we are at a point where nobody wants to take the initiative to create a complete list of people with leadership positions, get photos for each person, and keep it updated every six months. If anyone is willing to do this, we can reopen this issue to discuss it.
