### ISSUE TITLE
Missing words on camps/high adventure page

### ISSUE THREAD

**Issue by jackbuehner** [troop-370/troop370#7]
In the information about the page at the top, the last sense should be:
Information about the Troop's regular overnight trips can _be found_  on the troop calendar or on the campout schedule page.
(italics are what needs to be added)

**Comment by quintoncables** [comment]
It has been fixed.

**Comment by jackbuehner** [comment]
Fixed in commit 344c5e736d960bf951769a425dee592bae0575a4
