### ISSUE TITLE
Eagle scout chart is outdated

### ISSUE THREAD

**Issue by jackbuehner** [troop-370/troop370#9]
The table of Eagle Scouts and their projects needs to be updated to include Eagle Scouts from after January 2018. The table is linked to a Google Sheets file, so I just need an updated spreadsheet.

**Comment by quintoncables** [comment]
it also has "Jack Butlers" instead of jack butler

**Comment by jackbuehner** [comment]
@evansclan Can you provide an updated list through email?

**Comment by evansclan** [comment]
Here you go. I know the map has stopped working because Batchgeo has started charging due to some problem with Google Maps. We’ll need to find a new way of mapping this.

 


Harry

 


(file attached in email)

**Comment by jackbuehner** [comment]
Updated and typo is fixed
